### ISSUE TITLE
Add support for nested types in arbitrary context

### ISSUE THREAD

**Issue by fitdev** [Dreamescaper/IntelliSenseExtender#15]
It would be great if nested types (those defined inside of classes could also be shown).

**Comment by Dreamescaper** [comment]
Yeah, as far as I know, currently they are shown as 'simple' classes, and they are added without containing class. 
Definitely not the right behavior.

**Comment by Dreamescaper** [comment]
Ok, I see how it works now.

Currently those types are suggested (in broken way, but anyway) when target type is applicable in current context (when we're assigning values, providing arguments for method etc).

Do you think it makes any sense to show them in arbitrary context?

**Comment by fitdev** [comment]
You mean in attribute-like context as well? Maybe (provided they can be used as attributes. But I think the most important case is the current context, i.e. within member definition like a function or a property (i.e. assigning values, etc.)

**Comment by Dreamescaper** [comment]
No, not quite. 
How it currently works in Visual Studio by default - nested types are suggested only if this type is inferred from context. For example, when you have a method `public void SomeMethod(ContainingType.NestedType instance)`, then this type will be suggested after you write `SomeMethod(new `. But it is not suggested in other cases - when this type is not inferred from context.
Same situation is for enum member, for example.

I plan to fix issue that it is not working like that for unimported suggestions soon.

If you think, however, that those types should be shown in any context (like non-nested types), which means that behavior for imported suggestions should be changed as well - that's doable, but probably will take a while. 
I plan to refactor current code a lot, so it would make more sense to do after that.

**Comment by fitdev** [comment]
Oh I see what you mean! Thank you for this detailed explanation. Yeah, actually I would really like the later option, i.e. nested types "should be shown in any context (like non-nested types)". I have quite a few use cases for that.

For example, I like to define constant-like members in their own static classes, which in turn are defined inside a parent static class. So, for example: under static class `Chars` I would have another static class `Delimiters` that contain only delimiter-like const characters as members. So, when I am inside of a method, when I begin typing `Del...` without having `using static MyNamespace.Chars;` I would like to see `Chars.Delimiters` show up in the intellisense.

**Comment by Dreamescaper** [comment]
I have logged related issue I mentioned below: #18 
That one would be relatively easy to fix.

This one would probably wait until I refactor current code. Currently it would require to traverse all the types again, which is an expensive operation.

**Comment by Dreamescaper** [comment]
Done.
There's still some things I'd like to do before pushing it to marketplace, but if you want - you can grab latest build from appveyor and test it now.
