### ISSUE TITLE
Suggestion - better sort order of suggestions

### ISSUE THREAD

**Issue by bladeSk** [Dreamescaper/IntelliSenseExtender#22]
It would be very useful, if you could make the Intellisense popup display suggestions with better than the default sorting. Own/immediate members of a class should be displayed first and only then the inherited members. Another improvement could be displaying the members by category - fields, properties, methods, etc. Example:

* **OwnProperty**
* AnotherInheritedProperty
* InheritedProperty
* **OwnMethod**
* InheritedMethod

ReSharper does all of this, but they use a custom popup, so I'm not sure if this is possible with the default one.

Feel free to close this issue if it's out of the scope of this project.

**Comment by Dreamescaper** [comment]
Unfortunately, it's not currently possible (or I don't know how to do that, at least).
I can easily add new suggestions, but can't replace the order of existing ones.
