### ISSUE TITLE
Don't import "<global namespace>" when the class isn't in a namespace

### ISSUE THREAD

**Issue by pipe01** [Dreamescaper/IntelliSenseExtender#31]
This is useful the most when working with Unity, as the default is to not use any namespaces. Removing the item from the completion list would be fine, as importing it isn't needed.

**Comment by Dreamescaper** [comment]
Fixed in latest master. I need to fix several things before pushing it to Marketplace, but you can get VSIX from latest appveyor build if it bothers you a lot.

https://ci.appveyor.com/api/buildjobs/huaw5trf3rlmxj3t/artifacts/IntelliSenseExtender%2Fbin%2FRelease%2FIntelliSenseExtender.vsix

**Comment by pipe01** [comment]
Awesome, thanks!
