### ISSUE TITLE
Crashes visual studio

### ISSUE THREAD

**Issue by Magnus12** [Dreamescaper/IntelliSenseExtender#35]
As soon as I start typing visual studio crashes and restarts when the extension is enabled.
IntelliSenseExtender v. 0.9
Visual studio v. 15.8.4

**Comment by Dreamescaper** [comment]
Strange that I cannot reproduce that, and seems like you're not alone with that issue.
Could you try installing this VSIX and let me know if it helped?
https://ci.appveyor.com/api/buildjobs/t370leuqjl8g8ln8/artifacts/IntelliSenseExtender%2Fbin%2FRelease%2FIntelliSenseExtender.vsix
