### ISSUE TITLE
The Extension Causes Visual Studio to Crash.

### ISSUE THREAD

**Issue by pushqrdx** [Dreamescaper/IntelliSenseExtender#37]
So i managed to crash Visual Studio multiple times after i installed IntelliSense Extender but i think i'v finally pinned down an easy way to reproduce the issue.

Simply create an empty .cs file anywhere (without solution) and open it using Visual Studio. Once you start typing you'll crash. Now i tried to disable and re-enable every extension till i made sure that IntelliSense Extender is the cause for sure.

This extension is a life savior, and i really like it as a former ReSharper user, so a fix would be really appreciated.

Regards!

**Comment by Dreamescaper** [comment]
Fixed in latest version. Thanks for reporting!
