### ISSUE TITLE
Not suggesting anything (VS 15.7.6)

### ISSUE THREAD

**Issue by lrporto** [Dreamescaper/IntelliSenseExtender#49]
Installed in Visual Studio Community 2017 Version 15.7.6 and its not working. Options for IntelliSense Extender appears with everything marked as true. Tried the List example cited in overview and nothing. Tried closing the solution and openning it again, still nothing.

**Comment by Dreamescaper** [comment]
I'll make fresh install of 15.7.6, and will check whether I'm able to reproduce it.

In the meantime - could you try updating VS to latest version (15.9.5) and check whether it wokrs there?

**Comment by Dreamescaper** [comment]
Great!
I was able to reproduce it on version 15.7.6, and will try to fix it for older versions.
(I expected it to work on 15.4+ versions)

**Comment by Dreamescaper** [comment]
Closing, as no plans to support version 15.7.6
