### ISSUE TITLE
how about support IntelliSense and Highlight Raw Sql in C# string ?

### ISSUE THREAD

**Issue by sgf** [Dreamescaper/IntelliSenseExtender#50]
how about support IntelliSense and Highlight Raw Sql in C# string ?
and the Table source is C# Poco
and the DBFiled is C# Filed/Property.
when find the reference or change C# Filed/Property will effects the Raw Sql's string.

then we dont need any heavy weight Orm ,dont need linq or lambda,dont need EF,Nhibernate  etc.
just happy use such as Dapper.

Of course it will be a big and great job

```C#
[DBTable("TBL_User")]
public class User
{
public string Name;
public string Address;
}
//the User is type User,the Name is User.Name
Dapper.QueryByScript(new Sql(
@$"select * from User user where user.Name==@Name and @Address is not null)",
new{Name=“Jamie”}
);
```

i create a similar issue in project [VerifyRawSql](https://github.com/pkochubey/VerifyRawSql/)

**Comment by Dreamescaper** [comment]
That's probably not in the scope of this project, so I'm going to close the issue.
However, idea is certainly worth the effort to investigate.

I'll try to take a look at VerifyRawSql, and take a look, if it would be possible to integrate IntelliSense there.

**Comment by sgf** [comment]
thank you
