### ISSUE TITLE
Add support for Razor cshtml pages

### ISSUE THREAD

**Issue by 0xaryan** [Dreamescaper/IntelliSenseExtender#53]

**Comment by 0xaryan** [comment]
Isn't it possible to use System.Web.Razor.Parser.SyntaxTree and in general the Parser namespace utils to add @using directives in top of razor documents?

**Comment by daberni** [comment]
I had a look into this already too but wasn't successful on finding a solution either. The current roslyn parser is simply not compatible with Razor pages, it would require a complete standalone solution for them. Guess completely disabling it for Razor pages would be the best approach for the moment.

**Comment by Dreamescaper** [comment]
Completion are disabled for Razor files (thanks @daberni for PR!).
I'll reopen the issue, but as suggestion for improvement.
Maybe I'll be able to implement it later (not in the nearest future though)

**Comment by Dreamescaper** [comment]
Added corresponding bug to Roslyn:
https://github.com/dotnet/roslyn/issues/35172
