### ISSUE TITLE
Private method extensions are suggested

### ISSUE THREAD

**Issue by micdenny** [Dreamescaper/IntelliSenseExtender#57]
I don't expect the intellisense to show me the private methods extension took from external dependencies, because actually you cannot access those methods from outside the library it declares it.

Private methods extension should be suggested only when they come from the same project/library/dll where I'm writing code.

**Comment by Dreamescaper** [comment]
Certainly shouldn't be like that. Is that about extension methods?
Could you provide any example?

**Comment by micdenny** [comment]
> Is that about extension methods?

yes

> Could you provide any example?

coming... hold on

**Comment by micdenny** [comment]
sample:
[IntelliSenseExtenderPrivateExtensionMethods.zip](https://github.com/Dreamescaper/IntelliSenseExtender/files/2978969/IntelliSenseExtenderPrivateExtensionMethods.zip)

![image](https://user-images.githubusercontent.com/1633595/54542240-b95ab980-499b-11e9-970d-cb70221ed06e.png)

then when the using is imported of course the private method doesn't shows up anymore:

![image](https://user-images.githubusercontent.com/1633595/54543133-671a9800-499d-11e9-8a94-c774213a28b5.png)


![image](https://user-images.githubusercontent.com/1633595/54543111-5ec25d00-499d-11e9-959b-4d896fa195ce.png)

**Comment by Dreamescaper** [comment]
Yep, my bad. 
I checked for class accessibility, but not for member itself.

**Comment by Dreamescaper** [comment]
Thanks a lot for reporting the issue, and for great sample!
Fixed, will publish to marketplace a bit later. 

In the meanwhile you can test it from latest Appveyor build:
https://ci.appveyor.com/api/buildjobs/pu81ry5d9qk0vpcq/artifacts/IntelliSenseExtender%2Fbin%2FRelease%2Fnet472%2FIntelliSenseExtender.vsix
