### ISSUE TITLE
when type () of method, should not suggest completions

### ISSUE THREAD

**Issue by JerryJian** [Dreamescaper/IntelliSenseExtender#58]
for following codes
``` C#
connection.BeginTransaction()
```
When I type () of BeginTransaction, it suggests completions, next I will tap Tab and wish to jump out (), but the suggestion is typed in () witch is not what I want.

**Comment by Dreamescaper** [comment]
I have seen that behavior. Unfortunately, haven't found a good way to have auto-invoking IntelliSense for arguments and to fix this issue.

You can disable that auto invoking on IntelliSense Extender options page so far (to have native VS behavior).

Probably, I should disable it by default until fixed

**Comment by JerryJian** [comment]
Thank you very much. It solves the problem. The current behaviors is great for me.
