### ISSUE TITLE
Editor navigation crashes in VS 2019

### ISSUE THREAD

**Issue by xperiandri** [Dreamescaper/IntelliSenseExtender#59]
Extension conflicts with CodeRush IntelliRush feature in VS 2019 RTM causing editor not to handle up and down arrow keys.

**Comment by Dreamescaper** [comment]
Could you provide better description? 
Ideally with example project and screen recording.

I've never used CodeRush, but installed trial, and it seems to work fine for me:
![2019-04-07_11-13-41](https://user-images.githubusercontent.com/17177729/55682681-6f804600-593f-11e9-8aa7-6c38c418237e.gif)

**Comment by xperiandri** [comment]
I'll try to reproduce again

**Comment by Dreamescaper** [comment]
Closing bug. Please reopen if reproduces again
