### ISSUE TITLE
The extension isn't working.

### ISSUE THREAD

**Issue by bh-schmidt** [Dreamescaper/IntelliSenseExtender#68]
Hi, I found the following problem.

# Problem
If I create the following class with the `Guid` property and press `Ctrl + Space` then nothing appears, while it should recommend import the `using System;`.

```
namespace BigBrain.Provisionador.API
{
    public class Test
    {
        public Guid Id { get; set; }
    }
}
```
# Work-around
I found this problem more than once and I don't know why he happens, I tried reinstall the Visual Studio innumerous times but no one solved the problem, the work around I managed to do was install another version of Visual Studio (e.g. the problem is in Professional version then I install Community). It worked at first but I don't have another version to install. Is there a log file?

**Comment by bh-schmidt** [comment]
I just discovered that the extension is working fine, but I need to press `Ctrl + Space` and then `Alt + A` to show the unimported namespaces, is there a way to go back to the old configuration when I didn't need to press `Alt + A`?

**Comment by bh-schmidt** [comment]
I found a way to do it, problem solved.
I just needed to go to `Tools -> Options -> Text Editor -> Language (in my case C#) -> IntelliSense` and check the option `Show items from unimported namespaces`.

**Comment by Dreamescaper** [comment]
This functionality is part of VS itself now.
