### ISSUE TITLE
Extention stopped working since Visual Studio 2019 version 16.8

### ISSUE THREAD

**Issue by joost00719** [Dreamescaper/IntelliSenseExtender#69]
After updating to version 16.8 I noticed the extension stopped working.

**Comment by Dreamescaper** [comment]
Could you clarify what is not working specifically?
Note that VS has built-in functionality for import completions (see https://docs.microsoft.com/en-us/visualstudio/ide/reference/intellisense-completion-unimported-types-extension-methods?view=vs-2019), so you don't need this extension anymore if that's what you need.

**Comment by joost00719** [comment]
That is exactly what I was looking for.
Too bad MS ripped a good extension and made it their own (again).

**Comment by Dreamescaper** [comment]
Well, imported completions was one of the most requested features, so personally I'm very glad they have finally implemented it.

And their implementation is much more optimized in terms of performance.

**Comment by cjbush** [comment]
Would it be possible to update the README to include the info that Microsoft has added the functionality built in? It took me a little bit to find this and their implementation seems to not work when this plugin is enabled. I can submit a PR for it if you'd like.

**Comment by Dreamescaper** [comment]
Yeah, that certainly makes sense!
I'd be grateful if you submit PR, otherwise I'll update it a bit later.

**Comment by cjbush** [comment]
@Dreamescaper Sent you #70. Feel free to change whatever you want or I can change it however you'd like. Thanks so much for the plugin! I've used it for quite some time now.
