### ISSUE TITLE
[Feature Request]: Visual Studio 2022 Support

### ISSUE THREAD

**Issue by Wagnerp** [Dreamescaper/IntelliSenseExtender#71]
Hi @Dreamescaper 

I was wondering if there were any plans to support Visual Studio 2022?

**Comment by Dreamescaper** [comment]
I wasn't sure whether it makes a lot of sense, as most of the features are already available in VS out-of-the-box now.
Could you let me know which features are you interested in?

**Comment by Dreamescaper** [comment]
Here's the URL for VS2022 version:
https://ci.appveyor.com/api/buildjobs/adcs74forg4ch1w9/artifacts/IntelliSenseExtender%2Fbin%2FRelease%2Fnet472%2FIntelliSenseExtender.vsix

Please let me know if there are any issues.
I'll test it for a couple of days before publishing to marketplace.

**Comment by Wagnerp** [comment]
I was really interested in the automatic pulling in of the using statements. I will test it and report back if there are any issues.
