### ISSUE TITLE
Extension Method from referenced project import not showing

### ISSUE THREAD

**Issue by CharlesPublic** [Dreamescaper/IntelliSenseExtender#72]
I have a problem that Visual Studio 2022 doesn't automatically suggest Importing Namespaces for my Extension methods from referenced projects. 

**EDIT:** This Bug only occurs when i reference .NET 4.8 Projects from .NET 6 Projects.

If i don't have the using statement for the Extension method in my file then 

In Visual Studio 2019 i get the suggestion "using MyLibaryName" (This is great)
<img width="544" alt="only works in 2019" src="https://user-images.githubusercontent.com/44985274/154854949-db8ec1e1-a91d-4249-a5e6-f9d6789d7f03.png">

In Visual Studio 2022 i get no suggestion and have to manually import the namespace.

I tried this Extension but you wrote:
"Microsoft has added the ability to show items from unimported namespaces when autocompleting with Intellisense. Because of that this plugin does not provide unimported types completions. You can enable "Show items from unimported namespaces" in the Visual Studio options window." -> **This is not working for me**

So my question is could you show "Show items from unimported namespaces" again or maybe add an option for it.
That would be cool.

Cheers

**Comment by Dreamescaper** [comment]
The functionality to show unimported namespaces is removed from this repo, and won't be added back. Problem is that this functionality was implemented using a lot of internal APIs from Roslyn, which constantly changes with each VS release, so I can't simply leave it, I'd need to support it for each version.

But if you have any issues with built-in completions, you should report it to https://github.com/dotnet/roslyn repo.
