### ISSUE TITLE
Request: Respect the position of usings and sorting

### ISSUE THREAD

**Issue by zuckerthoben** [Dreamescaper/IntelliSenseExtender#9]
This extension automatically puts usings at the top of the file. StyleCop and other analyzers however are enforcing usings inside the namespace.

See:

```
// <copyright file="DbInitialization.cs" company="COMPANY">
// Copyright (c) COMPANY. All rights reserved.
// </copyright>

namespace COMPANY.DatabaseContext.Initialization
{
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using Microsoft.EntityFrameworkCore;
```

With the extension I end up with mixed using positions and I have to manually resort them everytime. Often times when you are in the flow of coding you arent actually noticing the namespace that the extender put in. 

So my request is to respect the position of current usings in a code file and to also respect the configured sorting rules.

**Comment by Dreamescaper** [comment]
Yeah...
Was already looking at that, and fixed partially (unreleased yet) - now it is added at sorted place, but still ignores usings inside namespaces.
Will take a look soon

**Comment by Dreamescaper** [comment]
Fixed in latest master.
Will try to release to Marketplace either today or tomorrow
